on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  sync:
    permissions:
        contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      - name: Install overleaf-sync and login
        env: 
          TOKEN: ${{ secrets.OVERLEAF_CREDENTIALS_BASE64 }}
        run: |
          wget https://github.com/YijunYuan/overleaf-sync/archive/refs/heads/github-action.zip -P $HOME
          cd $HOME
          unzip -o github-action.zip
          rm github-action.zip
          pip install -e ./overleaf-sync-github-action
          ols login -b64i $TOKEN
      - uses: actions/checkout@v4
      - name: Sync file to overleaf
        env:
          OVERLEAF_PROJECT_NAME: ${{ github.event.repository.name }}
          OVERLEAF_DELETE_OPTION: "d"
          OVERLEAF_KEEP_OLD: False
        run: |
          ols -l -i .gitignore --store-path $HOME/.olauth -n $OVERLEAF_PROJECT_NAME -dc $OVERLEAF_DELETE_OPTION -ko $OVERLEAF_KEEP_OLD
      - name: Clean up
        run: |
          rm -f $HOME/.olauth