on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
jobs:
  build:
    permissions:
        contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'
      - run: |
          wget https://github.com/YijunYuan/overleaf-sync/archive/refs/heads/github-action.zip
          unzip -o github-action.zip
          cd overleaf-sync-github-action
          pip install -e .
          cd ../
          rm -rf overleaf-sync-github-action
          rm github-action.zip
          ls